version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: site-ti-educacao-prod
    restart: unless-stopped
    ports:
      - "80:80" 
    volumes:
      - ./:/usr/share/nginx/html